server:
  port: 8081
oidc:
  issuer-uri: https://dev-737523.oktapreview.com/oauth2/default
  client-id: 0oa14vu0ojknUEao2357
  client-secret: IlH4AQR2nCiGyuI7ycZuzARc9XzZsqxruiEQGAzP

spring:
  security:
    oauth2:
      client:
        provider:
          okta:
            issuer-uri: ${oidc.issuer-uri}
        registration:
          okta:
            client-id: ${oidc.client-id}
            client-secret: ${oidc.client-secret}
      resourceserver:
        jwt:
          issuer-uri: ${oidc.issuer-uri}
  data:
    mongodb:
      authentication-database: wb24
      database: wb24
      host: localhost
      port: 27017
      username: wb24-admin
      password: wb24-admin
  profiles:
     active: Default